package org.xxp;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-19T14:17:27.394Z
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "xxp", 
                  wsdlLocation = "file:/C:/w4/src/main/resources/xxpPort.wsdl",
                  targetNamespace = "http://xxp.org/") 
public class Xxp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xxp.org/", "xxp");
    public final static QName XxpPort = new QName("http://xxp.org/", "xxpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/w4/src/main/resources/xxpPort.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Xxp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/w4/src/main/resources/xxpPort.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Xxp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Xxp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Xxp() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns XWebservice
     */
    @WebEndpoint(name = "xxpPort")
    public XWebservice getXxpPort() {
        return super.getPort(XxpPort, XWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XWebservice
     */
    @WebEndpoint(name = "xxpPort")
    public XWebservice getXxpPort(WebServiceFeature... features) {
        return super.getPort(XxpPort, XWebservice.class, features);
    }

}
