package org.xxp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2012-11-19T16:09:43.108Z
 * Generated source version: 2.4.9
 */
@WebServiceClient(name = "xxp",
        wsdlLocation = "classpath:xxpPort.wsdl",
        targetNamespace = "http://xxp.org/")
public class Xxp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xxp.org/", "xxp");
    public final static QName XxpPort = new QName("http://xxp.org/", "xxpPort");

    static {
        URL url = Xxp.class.getClassLoader().getResource("xxpPort.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(Xxp.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "classpath:xxpPort.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Xxp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Xxp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Xxp() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     * @return returns XWebservice
     */
    @WebEndpoint(name = "xxpPort")
    public XWebservice getXxpPort() {
        return super.getPort(XxpPort, XWebservice.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns XWebservice
     */
    @WebEndpoint(name = "xxpPort")
    public XWebservice getXxpPort(WebServiceFeature... features) {
        return super.getPort(XxpPort, XWebservice.class, features);
    }

}
